using AutoFactBot.Core.Abstractions;
using AutoFactBot.Core.Models;

namespace AutoFactBot.Application.Services
{
    public class DocumentsService : IDocumentsService
    {
        private readonly IDocumentsRepository _repository;

        public DocumentsService(IDocumentsRepository repository)
        {
            _repository = repository;
        }

        public async Task<List<DocumentModel>> GetAllDocuments()
        {
            return await _repository.GetAllDocuments();
        }

        public async Task<Guid> CreateDocument(DocumentModel document)
        {
            return await _repository.CreateDocument(document);
        }

        public async Task<Guid> UpdateDocument(
            #region Variables
            Guid id,
            string title,
            string carModel,
            string vinNumber,
            string engineNumber,
            string mileage,
            string owner,
            string countOwners,
            string year,
            string gearBox,
            string color,
            string countKeys,
            string interior,
            string interriorComment,
            string centrRightStand,
            string centrRightStandThickness,
            string centrLeftStand,
            string centrLeftStandThickness,
            string thresholdRight,
            string thresholdRightThickness,
            string thresholdLeft,
            string thresholdLeftThickness,
            string bodyComment,
            string glasses,
            string headlights,
            string mirrors,
            string glassComment,
            string engineOil,
            string gearBoxOil,
            string antifreeze,
            string brakeFluid,
            string steeringFluid,
            string engineSpaceComment,
            string yearTire,
            string remainingTire,
            string secondComplect,
            string wheelComplectComment,
            string wheelBearings,
            string shockAbsorbers,
            string suspensionArms,
            string stabilizer,
            string steeringTips,
            string steeringRack,
            string engineSump,
            string gearBoxSound,
            string otherElements,
            string engineError,
            string gearBoxError,
            string absError,
            string airbagError,
            string addControlUnits,
            string mileageCompliance,
            string computerDiagnosticComment,
            string gearBoxShifts,
            string gearBoxShiftsAcceleration,
            string gearBoxShiftsBreaking,
            string gearBoxShiftsCoasting,
            string gearBoxComment,
            string vibrationsDriving,
            string vibrationsBreaking,
            string soundsDriving,
            string soundsDrivingBumps,
            string suspentionComment,
            string brakePadWear,
            string brakeDiskWear,
            string brakeSystemComment,
            string folding,
            string adjustment,
            string heating,
            string seatHeating,
            string rearWindowHeating,
            string windshieldHeating,
            string controlsOperationComment,
            string checkingModes,
            string panelIndication,
            string awdComment,
            string coldStartEngine,
            string difficultStartEngine,
            string otherSounds,
            string strongVibration,
            string startEngineComment,
            string compressorOperation,
            string freonAvailability,
            string driveBeltCondition,
            string conditionerOperationComment,
            string restrictions,
            string subjectСollateral,
            string fines,
            string accidentArticipation,
            string carWanted,
            string vinNumberMatch,
            string legalCheckComment,
            string testDrive,
            string timingDrive,
            string engineOilAndFilter,
            string checkWheelsAngle,
            string recommendationsComment)
        #endregion
        {
            return await _repository.UpdateDocument(
            #region
                id,
                title,
                carModel,
                vinNumber,
                engineNumber,
                mileage,
                owner,
                countOwners,
                year,
                gearBox,
                color,
                countKeys,
                interior,
                interriorComment,
                centrRightStand,
                centrRightStandThickness,
                centrLeftStand,
                centrLeftStandThickness,
                thresholdRight,
                thresholdRightThickness,
                thresholdLeft,
                thresholdLeftThickness,
                bodyComment,
                glasses,
                headlights,
                mirrors,
                glassComment,
                engineOil,
                gearBoxOil,
                antifreeze,
                brakeFluid,
                steeringFluid,
                engineSpaceComment,
                yearTire,
                remainingTire,
                secondComplect,
                wheelComplectComment,
                wheelBearings,
                shockAbsorbers,
                suspensionArms,
                stabilizer,
                steeringTips,
                steeringRack,
                engineSump,
                gearBoxSound,
                otherElements,
                engineError,
                gearBoxError,
                absError,
                airbagError,
                addControlUnits,
                mileageCompliance,
                computerDiagnosticComment,
                gearBoxShifts,
                gearBoxShiftsAcceleration,
                gearBoxShiftsBreaking,
                gearBoxShiftsCoasting,
                gearBoxComment,
                vibrationsDriving,
                vibrationsBreaking,
                soundsDriving,
                soundsDrivingBumps,
                suspentionComment,
                brakePadWear,
                brakeDiskWear,
                brakeSystemComment,
                folding,
                adjustment,
                heating,
                seatHeating,
                rearWindowHeating,
                windshieldHeating,
                controlsOperationComment,
                checkingModes,
                panelIndication,
                awdComment,
                coldStartEngine,
                difficultStartEngine,
                otherSounds,
                strongVibration,
                startEngineComment,
                compressorOperation,
                freonAvailability,
                driveBeltCondition,
                conditionerOperationComment,
                restrictions,
                subjectСollateral,
                fines,
                accidentArticipation,
                carWanted,
                vinNumberMatch,
                legalCheckComment,
                testDrive,
                timingDrive,
                engineOilAndFilter,
                checkWheelsAngle,
                recommendationsComment);
            #endregion
        }

        public async Task<Guid> DeleteDocument(Guid id)
        {
            return await _repository.DeleteDocument(id);
        }
    }
}
