// <auto-generated />
using System;
using AutoFactBot.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoFactBot.Data.Migrations
{
    [DbContext(typeof(DocumentDbContext))]
    [Migration("20240419132836_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoFactBot.Data.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbsError")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccidentArticipation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddControlUnits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adjustment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AirbagError")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Antifreeze")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AwdComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BodyComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrakeDiskWear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrakeFluid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrakePadWear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrakeSystemComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CarWanted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CentrLeftStand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CentrLeftStandThickness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CentrRightStand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CentrRightStandThickness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckWheelsAngle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckingModes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColdStartEngine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompressorOperation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComputerDiagnosticComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConditionerOperationComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ControlsOperationComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountKeys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountOwners")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DifficultStartEngine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriveBeltCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineError")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineOil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineOilAndFilter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineSpaceComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineSump")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fines")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Folding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreonAvailability")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GearBox")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GearBoxComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GearBoxError")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GearBoxOil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GearBoxShifts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GearBoxShiftsAcceleration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GearBoxShiftsBreaking")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GearBoxShiftsCoasting")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GearBoxSound")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GlassComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Glasses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headlights")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Heating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Interior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InterriorComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LegalCheckComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mileage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MileageCompliance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mirrors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherElements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherSounds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PanelIndication")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RearWindowHeating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendationsComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemainingTire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Restrictions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatHeating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondComplect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShockAbsorbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoundsDriving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoundsDrivingBumps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stabilizer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartEngineComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SteeringFluid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SteeringRack")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SteeringTips")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrongVibration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectСollateral")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuspensionArms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuspentionComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestDrive")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThresholdLeft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThresholdLeftThickness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThresholdRight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThresholdRightThickness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimingDrive")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("VibrationsBreaking")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VibrationsDriving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VinNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VinNumberMatch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WheelBearings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WheelComplectComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WindshieldHeating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YearTire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("AutoFactBot.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AutoFactBot.Data.Entities.DocumentEntity", b =>
                {
                    b.HasOne("AutoFactBot.Data.Entities.UserEntity", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoFactBot.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
